{{- if and .Values.imagePullSecrets.create (not .Values.imagePullSecrets.existingSecret) }}
{{- if and .Values.imagePullSecrets.registry.username .Values.imagePullSecrets.registry.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "speedtest.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecrets.registry.server .Values.imagePullSecrets.registry.username .Values.imagePullSecrets.registry.password .Values.imagePullSecrets.registry.email (printf "%s:%s" .Values.imagePullSecrets.registry.username .Values.imagePullSecrets.registry.password | b64enc) | b64enc }}
{{- else }}
# WARNING: imagePullSecrets.create is true but username or password is missing
# Please provide both username and password in values.yaml:
# imagePullSecrets:
#   registry:
#     username: "your-github-username"
#     password: "your-github-token"
{{- end }}
{{- end }}
