apiVersion: v1
kind: Service
metadata:
  name: {{ include "speedtest.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "speedtest.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
    {{- if eq .Values.service.cloudProvider "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: {{ .Values.service.aws.scheme | default "internet-facing" }}
    {{- if .Values.service.aws.annotations }}
    {{- toYaml .Values.service.aws.annotations | nindent 4 }}
    {{- end }}
    {{- else if eq .Values.service.cloudProvider "azure" }}
    service.beta.kubernetes.io/azure-load-balancer-scheme: "Internet"
    {{- if .Values.service.azure.annotations }}
    {{- toYaml .Values.service.azure.annotations | nindent 4 }}
    {{- end }}
    {{- else if eq .Values.service.cloudProvider "gcp" }}
    {{- if .Values.service.gcp.annotations }}
    {{- toYaml .Values.service.gcp.annotations | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "speedtest.selectorLabels" . | nindent 4 }}
